name: Build Sphinx Docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      - name: Generate RST files
        run: sphinx-apidoc -o docs/source gps_norq --force

      - name: Build HTML documentation
        run: sphinx-build -b html docs/source docs/build/html
